INSERT INTO tb_category (name) VALUES ('Eletrônicos');
INSERT INTO tb_category (name) VALUES ('Roupas');
INSERT INTO tb_category (name) VALUES ('Computadores');
INSERT INTO tb_category (name) VALUES ('Celulares');
INSERT INTO tb_category (name) VALUES ('Acessórios Gamer');
INSERT INTO tb_category (name) VALUES ('Móveis');
INSERT INTO tb_category (name) VALUES ('Eletrodomésticos');
INSERT INTO tb_category (name) VALUES ('Ferramentas');
INSERT INTO tb_category (name) VALUES ('Esportes');
INSERT INTO tb_category (name) VALUES ('Beleza e Cuidados');
INSERT INTO tb_category (name) VALUES ('Automotivo');
INSERT INTO tb_category (name) VALUES ('Livros');
INSERT INTO tb_category (name) VALUES ('Brinquedos');
INSERT INTO tb_category (name) VALUES ('Papelaria');
INSERT INTO tb_category (name) VALUES ('Cozinha');
INSERT INTO tb_category (name) VALUES ('Pet Shop');
INSERT INTO tb_category (name) VALUES ('Câmeras e Fotografia');
INSERT INTO tb_category (name) VALUES ('Hardware');
INSERT INTO tb_category (name) VALUES ('Periféricos');
INSERT INTO tb_category (name) VALUES ('Jardinagem');
INSERT INTO tb_category (name) VALUES ('Iluminação');
INSERT INTO tb_category (name) VALUES ('Instrumentos Musicais');
INSERT INTO tb_category (name) VALUES ('Games');
INSERT INTO tb_category (name) VALUES ('Relojoaria');
INSERT INTO tb_category (name) VALUES ('Fitness');
INSERT INTO tb_category (name) VALUES ('Bolsas e Mochilas');
INSERT INTO tb_category (name) VALUES ('Saúde');
INSERT INTO tb_category (name) VALUES ('Nutrição');
INSERT INTO tb_category (name) VALUES ('Smart Home');
INSERT INTO tb_category (name) VALUES ('Energia Solar');
